=== cosmin-vestemean/retailers/documentatie/DXF KAUFLAND ROMANIA Electronic Invoice/XSD feedback message/docxchange-message.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) Docprocess S.R.L. 2015. All Rights Reserved.
  ~
  ~ No part of software may be distributed or reproduced without
  ~ Docprocess S.R.L.'s express consent.
  -->
<!-- versiunea 11112015 13.30 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" elementFormDefault="qualified" jaxb:version="2.0">
	<xs:element name="DXMessage">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="MessageDate"/>
				<xs:element ref="MessageTime"/>
				<xs:element ref="MessageOrigin"/>
				<xs:element ref="DocumentReference"/>
				<xs:element ref="DocumentUID"/>
				<xs:element ref="SupplierReceiverCode"/>
				<xs:element ref="DocumentResponse"/>
				<xs:element ref="DocumentDetail"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MessageDate" type="xs:date"/>
	<xs:element name="MessageTime" type="xs:time"/>
	<xs:element name="MessageOrigin" type="xs:string"/>
	<xs:element name="DocumentReference" type="xs:string"/>
	<xs:element name="DocumentUID" type="xs:string"/>
	<xs:element name="SupplierReceiverCode" type="xs:string"/>
	<xs:element name="DocumentResponse" type="xs:string"/>
	<xs:element name="DocumentDetail" type="xs:string"/>
</xs:schema>

=== cosmin-vestemean/retailers/data/aperak/xml/APERAK_DX01_005_20240131_01034351_VAT_RO15991149.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DXMessage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:/Users/rlixandru/Downloads/docxchange-message.xsd">
	<MessageDate>2024-01-31</MessageDate>
	<MessageTime>16:20:49</MessageTime>
	<MessageOrigin>RO15991149</MessageOrigin>
	<DocumentReference>18853</DocumentReference>
	<DocumentUID>DX01_099_20240131_01007246</DocumentUID>
	<SupplierReceiverCode>10011546</SupplierReceiverCode>
	<DocumentResponse>RECEPTIONAT</DocumentResponse>
	<DocumentDetail>- - 
ID document: DX01_099_20240131_01007246
Nume fisier: null
AS2MessageID: KAUFLAND-AS2-NEW-20240131-162039283-VuvP
MessageDigestNotificationID: KAUFLAND-AS2-NEW-20240131-162039283-VuvP
Status: Receptionat de Client
Mesaj: Documentul a fost receptionat de catre client
The document has been received by the customer.
</DocumentDetail>
</DXMessage>
